# Generated by Django 2.0 on 2017-12-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20171220_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('r', models.ManyToManyField(to='app02.Host')),
            ],
        ),
    ]
