# Generated by Django 2.0 on 2017-12-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_appcation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appcation',
            new_name='Application',
        ),
    ]
