# Generated by Django 2.0 on 2017-12-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_auto_20171221_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
