# Generated by Django 2.0 on 2017-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('email', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
    ]
