# Generated by Django 2.0 on 2017-12-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_application_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aobj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hobj',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
