# Generated by Django 2.0 on 2017-12-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20171217_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='venctor',
            new_name='vendor',
        ),
    ]
