# Generated by Django 2.0 on 2017-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='date_time',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
