# Generated by Django 2.0 on 2017-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171218_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '管理员'), (2, '普通用户')], null=True),
        ),
    ]
