# Generated by Django 2.0 on 2017-12-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_type',
            new_name='user_type_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default='1', on_delete=True, to='app01.UserGroup'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ip',
            field=models.GenericIPAddressField(help_text='ip地址', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=32, verbose_name='用户名'),
        ),
    ]
