# Generated by Django 2.0 on 2017-12-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171218_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ip',
        ),
    ]
