# Generated by Django 2.0 on 2017-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20171218_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(on_delete=True, to='app01.UserGroup'),
        ),
    ]
