# Generated by Django 2.0 on 2017-12-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20171217_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.AutoField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
